import type { StyleDefinitions } from "../domain/style";

export const STYLE_DEFINITIONS = {
  "minimal-product-keynote": { id: "minimal-product-keynote", name: { en: "Minimal Product Keynote", zh: "极简产品主题演讲" }, band: "minimal-keynote" },
  "objective-swiss-grid": { id: "objective-swiss-grid", name: { en: "Objective Swiss Grid", zh: "客观瑞士网格" }, band: "minimal-keynote" },
  "wabi-sabi-ceramic": { id: "wabi-sabi-ceramic", name: { en: "Wabi-Sabi Ceramic", zh: "侘寂陶器" }, band: "minimal-keynote" },
  "interactive-dialogue-stage": { id: "interactive-dialogue-stage", name: { en: "Interactive Dialogue Stage", zh: "互动对话舞台" }, band: "minimal-keynote" },
  "cyanotype-drafting-table": { id: "cyanotype-drafting-table", name: { en: "Cyanotype Drafting Table", zh: "蓝图制图台" }, band: "minimal-keynote" },
  "kinetic-type-punchline": { id: "kinetic-type-punchline", name: { en: "Kinetic Type Punchline", zh: "动感字体金句" }, band: "minimal-keynote" },
  "sketch-board-emoji": { id: "sketch-board-emoji", name: { en: "Sketch Board Emoji", zh: "草图白板表情" }, band: "minimal-keynote" },
  "spotlight-quote-poster": { id: "spotlight-quote-poster", name: { en: "Spotlight Quote Poster", zh: "聚光引言海报" }, band: "minimal-keynote" },
  "subway-map-of-intent": { id: "subway-map-of-intent", name: { en: "Subway Map of Intent", zh: "意图地铁图" }, band: "balanced-hybrid" },
  "benchmark-matrix": { id: "benchmark-matrix", name: { en: "Benchmark Matrix", zh: "基准矩阵" }, band: "balanced-hybrid" },
  "signal-pipeline-flow": { id: "signal-pipeline-flow", name: { en: "Signal Pipeline Flow", zh: "信号管道流" }, band: "balanced-hybrid" },
  "engineering-whiteboard-explainer": { id: "engineering-whiteboard-explainer", name: { en: "Engineering Whiteboard Explainer", zh: "工程讲解白板" }, band: "balanced-hybrid" },
  "soft-pastel-friendly": { id: "soft-pastel-friendly", name: { en: "Soft Pastel Friendly", zh: "柔和粉彩友好" }, band: "balanced-hybrid" },
  "kitchen-prep-station": { id: "kitchen-prep-station", name: { en: "Kitchen Prep Station", zh: "厨房备料台" }, band: "balanced-hybrid" },
  "collaborative-pairing-board": { id: "collaborative-pairing-board", name: { en: "Collaborative Pairing Board", zh: "协作配对板" }, band: "balanced-hybrid" },
  "studio-mixing-console": { id: "studio-mixing-console", name: { en: "Studio Mixing Console", zh: "录音混音控制台" }, band: "balanced-hybrid" },
  "debug-reaction-board": { id: "debug-reaction-board", name: { en: "Debug Reaction Board", zh: "调试反应面板" }, band: "balanced-hybrid" },
  "front-page-broadsheet": { id: "front-page-broadsheet", name: { en: "Front-Page Broadsheet", zh: "头版大报" }, band: "editorial-print" },
  "magazine-masthead": { id: "magazine-masthead", name: { en: "Magazine Masthead", zh: "杂志刊头" }, band: "editorial-print" },
  "warm-editorial-feature": { id: "warm-editorial-feature", name: { en: "Warm Editorial Feature", zh: "暖色专题特稿" }, band: "editorial-print" },
  "scholars-vellum": { id: "scholars-vellum", name: { en: "Scholar's Vellum", zh: "学者羊皮卷" }, band: "editorial-print" },
  "solar-biennale-poster": { id: "solar-biennale-poster", name: { en: "Solar Biennale Poster", zh: "日光双年展海报" }, band: "editorial-print" },
  "duotone-session": { id: "duotone-session", name: { en: "Duotone Session", zh: "双调录制" }, band: "editorial-print" },
  "riso-print-zine": { id: "riso-print-zine", name: { en: "Riso Print Zine", zh: "孔版印刷杂志" }, band: "editorial-print" },
  "analog-cutout-collage": { id: "analog-cutout-collage", name: { en: "Analog Cutout Collage", zh: "模拟剪纸拼贴" }, band: "editorial-print" },
  "woodblock-floating-world": { id: "woodblock-floating-world", name: { en: "Woodblock Floating-World", zh: "木版浮世绘" }, band: "craft-cultural" },
  "botanical-specimen-plate": { id: "botanical-specimen-plate", name: { en: "Botanical Specimen Plate", zh: "植物标本板" }, band: "craft-cultural" },
  "machine-age-deco": { id: "machine-age-deco", name: { en: "Machine-Age Deco", zh: "机器时代装饰艺术" }, band: "craft-cultural" },
  "expedition-screenprint": { id: "expedition-screenprint", name: { en: "Expedition Screenprint", zh: "探险丝网印" }, band: "craft-cultural" },
  "cassette-era-packaging": { id: "cassette-era-packaging", name: { en: "Cassette-Era Packaging", zh: "卡带时代包装" }, band: "craft-cultural" },
  "neo-brutalist-bulletin": { id: "neo-brutalist-bulletin", name: { en: "Neo-Brutalist Bulletin", zh: "新粗野公告" }, band: "craft-cultural" },
  "red-wedge-agitprop": { id: "red-wedge-agitprop", name: { en: "Red-Wedge Agitprop", zh: "红楔宣传画" }, band: "craft-cultural" },
  "mechanical-scoring-funnel": { id: "mechanical-scoring-funnel", name: { en: "Mechanical Scoring Funnel", zh: "机械评分漏斗" }, band: "craft-cultural" },
  "liquid-glass": { id: "liquid-glass", name: { en: "Liquid Glass", zh: "液态玻璃" }, band: "contemporary-digital" },
  "retro-windows": { id: "retro-windows", name: { en: "Retro Windows", zh: "复古 Windows" }, band: "contemporary-digital" },
  "mid-century-grove": { id: "mid-century-grove", name: { en: "Mid-Century Grove", zh: "中世纪林间" }, band: "contemporary-digital" },
  "after-hours-luxe": { id: "after-hours-luxe", name: { en: "After-Hours Luxe", zh: "深夜奢华" }, band: "contemporary-digital" },
  "operating-manual": { id: "operating-manual", name: { en: "Operating Manual", zh: "操作手册" }, band: "contemporary-digital" },
  "widescreen-title-card": { id: "widescreen-title-card", name: { en: "Widescreen Title Card", zh: "宽屏标题卡" }, band: "contemporary-digital" },
  "blackboard-chalk-talk": { id: "blackboard-chalk-talk", name: { en: "Blackboard Chalk Talk", zh: "黑板粉笔演讲" }, band: "contemporary-digital" },
  "arcade-boss-fight": { id: "arcade-boss-fight", name: { en: "Arcade Boss Fight", zh: "街机 Boss 战" }, band: "contemporary-digital" },
  "research-memo": { id: "research-memo", name: { en: "Research Memo", zh: "研究备忘录" }, band: "text-report" },
  "decision-record": { id: "decision-record", name: { en: "Decision Record", zh: "决策记录" }, band: "text-report" },
  "maintainer-issue-brief": { id: "maintainer-issue-brief", name: { en: "Maintainer Issue Brief", zh: "维护者问题简报" }, band: "text-report" },
  "field-notes-report": { id: "field-notes-report", name: { en: "Field Notes Report", zh: "田野笔记报告" }, band: "text-report" },
  "annotated-source-diff": { id: "annotated-source-diff", name: { en: "Annotated Source & Diff", zh: "注解源码与差异" }, band: "text-report" },
  "checklist-ledger": { id: "checklist-ledger", name: { en: "Checklist Ledger", zh: "检查清单台账" }, band: "text-report" },
  "context-bento-box": { id: "context-bento-box", name: { en: "Context Bento Box", zh: "上下文便当盒" }, band: "text-report" },
  "object-metaphor-hero": { id: "object-metaphor-hero", name: { en: "Object Metaphor Hero", zh: "物体隐喻主视觉" }, band: "text-report" },
} as const satisfies StyleDefinitions;
