import { useEffect, useRef, useState } from "react";
import type { StyleRegistryEntry } from "../../types";

export interface TopicBarProps {
  style: StyleRegistryEntry;
  currentTopicId: string;
  language: "en" | "zh";
  onGoOverview: () => void;
  onSelectTopic: (topicId: string) => void;
}

export default function TopicBar({
  style,
  currentTopicId,
  language,
  onGoOverview,
  onSelectTopic,
}: TopicBarProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  const currentTopicIndex = style.topics.findIndex(
    (topic) => topic.id === currentTopicId,
  );
  const activeTopicIndex = currentTopicIndex >= 0 ? currentTopicIndex : 0;
  const currentTopicEntry = style.topics[activeTopicIndex];
  const totalTopics = style.topics.length;

  if (!currentTopicEntry) return null;

  const styleName = style.name[language];
  const hasMultiple = totalTopics > 1;
  const activeTopicId = currentTopicEntry.id;
  const switcherLabel = language === "zh" ? "主题" : "Topics";
  const currentPosition = `${activeTopicIndex + 1}/${totalTopics}`;
  const currentTopic = currentTopicEntry.topic[language];

  useEffect(() => {
    if (!menuOpen) return;

    const handleMouseDown = (event: MouseEvent) => {
      if (!menuRef.current?.contains(event.target as Node)) {
        setMenuOpen(false);
      }
    };

    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") setMenuOpen(false);
    };

    document.addEventListener("mousedown", handleMouseDown);
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("mousedown", handleMouseDown);
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [menuOpen]);

  return (
    <div
      data-testid="topic-bar"
      className="h-7 flex items-center px-3 gap-2 text-xs border-b border-ink/10 bg-chrome/60"
      style={{ flexShrink: 0 }}
    >
      <button
        type="button"
        onClick={onGoOverview}
        className="min-w-0 max-w-[220px] flex items-center gap-1.5 text-ink/60 hover:text-ink transition-colors"
        title={language === "zh" ? "返回总览" : "Return to overview"}
      >
        <span className="font-mono text-[11px]">{style.id}</span>
        <span className="text-ink/20">·</span>
        <span className="font-medium truncate max-w-[160px]">
          {styleName}
        </span>
      </button>

      <svg
        width="12"
        height="12"
        viewBox="0 0 12 12"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        className="text-ink/20 shrink-0"
      >
        <polyline points="4,2 8,6 4,10" />
      </svg>

      <div className="hidden sm:flex min-w-0 items-center gap-2">
        <span className="text-ink/80 font-medium truncate max-w-[200px]">
          {currentTopic}
        </span>
        <span
          className="text-[10px] px-1.5 py-0.5 rounded bg-ink/[0.06] text-ink/50 font-mono shrink-0"
          title={`Generated by ${currentTopicEntry.model}`}
        >
          {currentTopicEntry.model}
        </span>
      </div>

      <div className="flex-1" />

      {hasMultiple ? (
        <div
          ref={menuRef}
          className="relative shrink-0"
          onMouseEnter={() => setMenuOpen(true)}
          onMouseLeave={() => setMenuOpen(false)}
        >
          <button
            type="button"
            data-testid="topic-switcher"
            aria-haspopup="menu"
            aria-expanded={menuOpen}
            aria-label={switcherLabel}
            onClick={() => setMenuOpen(true)}
            className="h-6 max-w-[150px] px-2 rounded-md border border-ink/10 bg-ink/[0.05] hover:bg-ink/[0.09] flex items-center gap-1.5 text-ink/70 transition-colors"
            title={language === "zh" ? "切换主题" : "Switch topic"}
          >
            <span className="hidden sm:inline text-[10px] font-medium">
              {switcherLabel}
            </span>
            <span className="font-mono text-[10px] shrink-0">
              {currentPosition}
            </span>
            <svg
              width="10"
              height="10"
              viewBox="0 0 10 10"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.4"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="shrink-0"
              style={{
                transform: menuOpen ? "rotate(180deg)" : "rotate(0deg)",
              }}
            >
              <polyline points="2,3.5 5,6.5 8,3.5" />
            </svg>
          </button>

          {menuOpen && (
            <div
              data-testid="topic-menu-hover-zone"
              className="absolute right-0 top-full w-72 max-w-[calc(100vw-1rem)] pt-1 z-50"
            >
              <div
                data-testid="topic-menu"
                role="menu"
                className="rounded-md border border-ink/10 bg-elevated shadow-lg p-1"
              >
                {style.topics.map((topic, index) => {
                  const isActive = topic.id === activeTopicId;
                  const label = `${index + 1}`;

                  return (
                    <button
                      key={topic.id}
                      type="button"
                      role="menuitem"
                      data-testid={`topic-option-${topic.id}`}
                      aria-current={isActive ? "true" : undefined}
                      aria-pressed={isActive}
                      onClick={() => {
                        if (!isActive) onSelectTopic(topic.id);
                        setMenuOpen(false);
                      }}
                      className={[
                        "w-full min-w-0 px-2.5 py-2 rounded-[5px] flex items-center gap-2 text-left transition-colors",
                        isActive
                          ? "bg-ink/[0.09] text-ink"
                          : "text-ink/65 hover:bg-ink/[0.06]",
                      ].join(" ")}
                    >
                      <span className="w-3 text-center text-[10px] text-ink/45">
                        {isActive ? "*" : ""}
                      </span>
                      <span className="font-mono text-[10px] text-ink/55 shrink-0">
                        {label}
                      </span>
                      <span className="min-w-0 flex-1 truncate text-[11px]">
                        {topic.topic[language]}
                      </span>
                      <span className="font-mono text-[9px] text-ink/35 shrink-0">
                        {topic.model}
                      </span>
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      ) : (
        <span
          data-testid="topic-count"
          className="text-[10px] font-mono text-ink/30 shrink-0"
        >
          {activeTopicIndex + 1}/{totalTopics}
        </span>
      )}
    </div>
  );
}
