import { useState, useRef, useEffect, useCallback } from "react";
import type { StyleRegistryEntry } from "../../types";

export interface VersionBarProps {
  style: StyleRegistryEntry;
  currentVersionId: string;
  language: "en" | "zh";
  onGoOverview: () => void;
  onSelectVersion: (versionId: string) => void;
}

export default function VersionBar({
  style,
  currentVersionId,
  language,
  onGoOverview,
  onSelectVersion,
}: VersionBarProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  const currentVersionIndex = style.versions.findIndex(
    (v) => v.id === currentVersionId,
  );
  const currentVersion =
    style.versions[currentVersionIndex >= 0 ? currentVersionIndex : 0];
  const totalVersions = style.versions.length;

  // Close menu on outside click
  useEffect(() => {
    if (!menuOpen) return;
    const handleClick = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setMenuOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [menuOpen]);

  const toggleMenu = useCallback(() => {
    setMenuOpen((prev) => !prev);
  }, []);

  if (!currentVersion) return null;

  const styleName = style.name[language];
  const hasMultiple = totalVersions > 1;

  return (
    <div
      data-testid="version-bar"
      className="h-7 flex items-center px-3 gap-2 text-xs border-b border-ink/10 bg-chrome/50"
      style={{ flexShrink: 0 }}
    >
      {/* Style identifier — clickable to return to overview */}
      <button
        type="button"
        onClick={onGoOverview}
        className="flex items-center gap-1.5 text-ink/60 hover:text-ink transition-colors"
        title={language === "zh" ? "返回总览" : "Return to overview"}
      >
        <span className="font-mono text-[11px]">{style.id}</span>
        <span className="text-ink/20">·</span>
        <span className="font-medium truncate max-w-[160px]">
          {styleName}
        </span>
      </button>

      {/* Separator */}
      <svg
        width="12"
        height="12"
        viewBox="0 0 12 12"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
        className="text-ink/20 shrink-0"
      >
        <polyline points="4,2 8,6 4,10" />
      </svg>

      {/* Topic */}
      <span className="text-ink/80 font-medium truncate max-w-[200px]">
        {currentVersion.topic}
      </span>

      {/* Spacer */}
      <div className="flex-1" />

      {/* Model label */}
      <span
        className="text-[10px] px-1.5 py-0.5 rounded bg-ink/[0.06] text-ink/50 font-mono shrink-0"
        title={`Generated by ${currentVersion.model}`}
      >
        {currentVersion.model}
      </span>

      {/* Version indicator */}
      {hasMultiple ? (
        <button
          type="button"
          onClick={toggleMenu}
          className="text-[10px] font-mono text-ink/50 hover:text-ink transition-colors shrink-0"
          title={language === "zh" ? "切换版本" : "Switch version"}
        >
          v{currentVersionIndex + 1}/{totalVersions}
        </button>
      ) : (
        <span className="text-[10px] font-mono text-ink/30 shrink-0">
          v1/1
        </span>
      )}

      {/* More menu dropdown */}
      <div className="relative" ref={menuRef}>
        <button
          type="button"
          onClick={toggleMenu}
          className="p-0.5 rounded hover:bg-ink/10 text-ink/40 hover:text-ink/70 transition-colors"
          aria-label={language === "zh" ? "版本选项" : "Version options"}
          aria-expanded={menuOpen}
        >
          <svg
            width="14"
            height="14"
            viewBox="0 0 14 14"
            fill="currentColor"
          >
            <circle cx="7" cy="3" r="1.2" />
            <circle cx="7" cy="7" r="1.2" />
            <circle cx="7" cy="11" r="1.2" />
          </svg>
        </button>

        {menuOpen && (
          <div
            className="absolute right-0 top-full mt-1 w-52 rounded-lg border border-ink/10 bg-elevated shadow-lg z-50 py-1"
            role="menu"
          >
            {/* Version list */}
            {hasMultiple && (
              <>
                <div className="px-3 py-1.5 text-[10px] font-semibold uppercase tracking-wider text-ink/40">
                  {language === "zh" ? "版本" : "Versions"}
                </div>
                {style.versions.map((v, i) => {
                  const isActive = v.id === currentVersionId;
                  return (
                    <button
                      key={v.id}
                      type="button"
                      role="menuitem"
                      onClick={() => {
                        onSelectVersion(v.id);
                        setMenuOpen(false);
                      }}
                      className={[
                        "w-full flex items-center gap-2 px-3 py-1.5 text-left text-xs transition-colors",
                        isActive
                          ? "bg-ink/10 font-medium"
                          : "hover:bg-ink/5",
                      ].join(" ")}
                    >
                      <span className="font-mono text-ink/40 w-5">
                        v{i + 1}
                      </span>
                      <span className="truncate flex-1">{v.topic}</span>
                      <span className="text-[9px] text-ink/30 font-mono">
                        {v.model}
                      </span>
                    </button>
                  );
                })}
                <div className="my-1 border-t border-ink/10" />
              </>
            )}

            {/* Version info */}
            <div className="px-3 py-2">
              <div className="text-[10px] font-semibold uppercase tracking-wider text-ink/40 mb-1">
                {language === "zh" ? "版本信息" : "Version Info"}
              </div>
              <div className="space-y-1">
                <div className="flex justify-between gap-2">
                  <span className="text-ink/50">
                    {language === "zh" ? "模型" : "Model"}
                  </span>
                  <span className="font-mono text-ink/70">
                    {currentVersion.model}
                  </span>
                </div>
                <div className="flex justify-between gap-2">
                  <span className="text-ink/50">
                    {language === "zh" ? "题材" : "Topic"}
                  </span>
                  <span className="text-ink/70 truncate max-w-[120px]">
                    {currentVersion.topic}
                  </span>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
